# Generated by Django 5.1 on 2024-12-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='message',
            new_name='password',
        ),
    ]
