# Generated by Django 5.0 on 2025-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='education_level',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='experience_level',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_market_demand_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
