# Generated by Django 5.0 on 2025-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_careerroadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_name',
            field=models.CharField(default='Unknown Career', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roadmap',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
