# Generated by Django 5.0 on 2025-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile_career_name_userprofile_roadmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roadmap',
            field=models.JSONField(default=list),
        ),
    ]
