# Generated by Django 5.0 on 2025-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userprofile_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roadmap',
            field=models.JSONField(default=dict),
        ),
    ]
