# Generated by Django 5.0 on 2025-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(default=dict),
        ),
    ]
