# Generated by Django 5.0 on 2025-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
