# Generated by Django 5.0 on 2025-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile_current_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transition_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
