# Generated by Django 5.0 on 2025-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile_transition_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
