# Generated by Django 5.0 on 2025-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
