# Generated by Django 5.0 on 2025-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
